name: copyright-preamble
on: 
  push:
    branches: 
      - master
jobs:
  Write-copyright-preamble-to-files:
    runs-on: ubuntu-latest
    steps:
      # Checking out the repository which is to be actioned
      - uses: actions/checkout@v2
      # Implementing action on repository
      - uses: VinnyBabuManjaly/copyright-action@v1.0.0
        with:
          CopyrightString: 'Copyright 2021 Thomas Battenfeld, Alexander Thomas, Johannes Köster.\n' + 
          'Licensed under the GNU GPLv3 license (https://opensource.org/licenses/GPL-3.0)\n' + 
          'This file may not be copied, modified, or distributed\n' + 
          'except according to those terms.\n'
          FileType: '.py, .smk'
          Path: '../../workflow/rules, ../../workflow/scripts/'
          IgnorePath: ''
      # Creates pull request with all changes in file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
